
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: postgres-db
  name: postgres-db
spec:
  containers:
  - env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    image: postgres
    name: postgres-db
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pdata
    ports:
      - containerPort: 5432
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: pdata
      persistentVolumeClaim:
        claimName: postgres-pvc

status: {}
