apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: postgres-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce